apiVersion: v1
kind: Secret
metadata:
  name: {{ include "property-search.fullname" . }}-secrets
  labels:
    {{- include "property-search.labels" . | nindent 4 }}
type: Opaque
stringData:
  datadog-api-key: {{ .Values.secrets.datadogApiKey | quote }}
  rentcast-api-key: {{ .Values.secrets.rentcastApiKey | quote }}
  postgres-url: {{ .Values.secrets.postgresUrl | quote }}
